services:
  mqtt:
    build:
      context: src/fake-sensor-data/mqtt
      dockerfile: Dockerfile
    ports:
      - 1883:1883
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'mosquitto_sub -h localhost -p 1883 -E -i healthcheck-client --insecure -t test']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s
    volumes:
      - mqtt:/mosquitto/data

  fake-sensor-data:
    build:
      context: src/fake-sensor-data
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_healthy
    environment:
      - MQTT_HOST=mqtt

  sensors:
    depends_on:
      kafka:
        condition: service_healthy
      mqtt:
        condition: service_healthy

volumes:
  mqtt:
