services:
  mqtt:
    build:
      context: src/fake-sensor-data/mqtt
      dockerfile: Dockerfile
    ports:
      - 1883:1883
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'mosquitto_sub -h localhost -p 1883 -E -i healthcheck-client --insecure -t test']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s
    volumes:
      - mqtt:/mosquitto/data

  fake-sensor-data:
    profiles:
      - fake-sensors
    build:
      context: src/fake-sensor-data
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_healthy
    environment:
      - MQTT_HOST=mqtt

  sensors:
    depends_on:
      kafka:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    environment:
      - MQTT_HOST=mqtt

  mock-robot:
    image: mockserver/mockserver
    ports:
      - '5001:5001'
    environment:
      - MOCKSERVER_SERVER_PORT=5001
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/tmp/mockserver/robot.json
    volumes:
      - ./src/mockserver/robot.json:/tmp/mockserver/robot.json:ro
    restart: unless-stopped

  mock-robot-conveyor:
    image: mockserver/mockserver
    ports:
      - '5000:5000'
    environment:
      - MOCKSERVER_SERVER_PORT=5000
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/tmp/mockserver/robot_and_conveyor.json
    volumes:
      - ./src/mockserver/robot_and_conveyor.json:/tmp/mockserver/robot_and_conveyor.json:ro
    restart: unless-stopped

volumes:
  mqtt:
