services:
  mqtt:
    build:
      context: src/fake-sensor-data/mqtt
      dockerfile: Dockerfile
    ports:
      - 1883:1883
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'mosquitto_sub -h localhost -p 1883 -E -i healthcheck-client --insecure -t test']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s
    volumes:
      - mqtt:/mosquitto/data

volumes:
  mqtt:
