services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 2181:2181
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      #     KAFKA_ADVERTISED_HOST_NAME: 192.168.1.173
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.173
      KAFKA_ADVERTISED_PORT: 9092
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.173:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    profiles:
      - consumer
      - producer


  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.173:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: "true"
      KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_CFG_HEARTBEAT_INTERVAL_MS: 1000
      KAFKA_CFG_SESSION_TIMEOUT_MS: 10000
      KAFKA_CFG_REBALANCE_TIMEOUT_MS: 15000

    depends_on:
      - zookeeper
    profiles:
      - fault

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    ports:
      - 9093:9093
      - 7204:7204
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.173:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9093
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: "true"
      KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_CFG_HEARTBEAT_INTERVAL_MS: 1000
      KAFKA_CFG_SESSION_TIMEOUT_MS: 10000
      KAFKA_CFG_REBALANCE_TIMEOUT_MS: 15000
    depends_on:
      - zookeeper
    profiles:
      - fault

  kafka3:
    image: bitnami/kafka:latest
    container_name: kafka3
    ports:
      - 9094:9094
      - 7205:7205
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.173:9094
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9094
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: "true"
      KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_CFG_HEARTBEAT_INTERVAL_MS: 1000
      KAFKA_CFG_SESSION_TIMEOUT_MS: 10000
      KAFKA_CFG_REBALANCE_TIMEOUT_MS: 15000
    depends_on:
      - zookeeper
    profiles:
      - fault


#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - 3000:3000
#    volumes:
#      - ./grafana-storage:/var/lib/grafana
#      - /Users/Simon_1/Documents/HSG/MCS/FS25/Event-driven and Process-oriented Architectures/Project/exercise1/faultToleranceTest/logs/aggregated:/var/lib/grafana/logs
#      - ./provisioning:/etc/grafana/provisioning
#      - ./provisioning/grafana.ini:/etc/grafana/grafana.ini # Map grafana.ini specifically
#    environment:
#      GF_SECURITY_ADMIN_USER: admin
#      GF_SECURITY_ADMIN_PASSWORD: admin
#    profiles:
#      - fault
#
#volumes:
#  grafana-storage:
#    driver: local